### PR TITLE
Added support for building using the dotnet cli.

### PR DESCRIPTION
**Pull request by DarkKilauea**
This request also provides support for .NET Core 1.0 and support for building and running on Linux and Mac OS X.

All samples are currently compiling under all platforms, except for the TwitterBot sample which has dependencies that only support the full .NET Framework (it compiles fine for Windows only however). 

The test suite runs and passes on Windows, Linux, and Mac OS X.  I also ran the MarkovTextBot sample on both Windows and Mac OS X to smoke test the samples in general.

I have not updated the CI build definitions since I am not familiar enough with them.  Some help here would be appreciated.

### CODE REVIEW

**Comment by paralin** [comment]
Great work. Will review in the coming days. Probably will merge to another branch and fix the automated ci testing.

**Comment by DarkKilauea** [comment]
It seems that .NET Core RTM was released yesterday.  I'm going to take some time to update this pull request and test that everything works with the final released framework.

If all goes well I'll have something for you tonight.

**Comment by paralin** [comment]
I noticed the update came out and was going to ask actually. Thank you for upgrading it. Looking forward to using a version of dotnet that isn't broken :)

**Comment by DarkKilauea** [comment]
The upgrade to RTM was pretty straight forward.  I went ahead and squashed the update into the previous commit to keep the history sane.

**Comment by paralin** [comment]
Merged into new branch chore/dotnetcore and tracking work in #20

**Pull request closed without merging**
