### PR TITLE
Added Visual Studio code folder to .gitignore

### PR DESCRIPTION
**Pull request by oreleraki**

### CODE REVIEW

**Comment by oreleraki** [comment]
@alexreg mind double check the permissions, it's still on the same status
image

**Comment by oreleraki** [comment]
@alexreg, As part of "github protection branch", this step prevents the merging
image
After searching i've found that TravisCI GitHub App will not send any more git commit statuses, thus stop alerting github of any status changes.

In here there is the Issue + Remedy of the issue, please fix it so i could start merging and update the library, thank you.
Same issue: https://github.com/travis-ci/travis-ci/issues/10204

**Comment by oreleraki** [comment]
@alexreg, I don't know if you had to chance to see my last message. If you will, i could continue working and improving the library when you will disable github features i mentioned in the last message. Thank you alot.

**Comment by oreleraki** [comment]
I don't know if you had to chance to see my last message. If you will, i could continue working and improving the library when you will disable github features i mentioned in the last message. And also disabling the reviewer option will also help. Thank you a lot.

**Comment by alexreg** [comment]
@oreleraki Sorry for the delay getting back to you. That should be done now, and also GitHub should no longer require a review before allowing a PR to merge. (Obviously, this makes sense with only one maintainer.)

**Pull request merged**
