### PR TITLE
Fix ssl

### PR DESCRIPTION
**Pull request by izrik**
This PR fixes ssl connections. It also updates the `connect` command to allow the sample bots to make ssl connections. It still needs a little bit of cleanup, and probably some more rigorous testing. I'll try to add another couple commits tomorrow.

### CODE REVIEW

**Comment by izrik** [comment]
@alexreg I can't quite figure out the build/test system. It passed on Appveyor, but failed on Travis. For the life of me, I can't tell what went wrong in the travis build, or even what assertion failed.

On my local machine, on the command line, the test set sometimes passes, but sometimes fails. The failures are not consistent. I can't get it to run properly from within Xamarin Studio/MonoDevelop, even after cloning a MonoDevelop-compatible NUnit project.

Am I doing something wrong? What IDE, if any, do you use to run the tests?

**Comment by alexreg** [comment]
Hmm. Visual Studio always ran the tests fine for me. What's the specific problem?

I'll be honest, the build system isn't totally clear with me either now, since I accepted some big changes from a contributor, and I myself haven't touched the source code in some time.

@matthid, if you wouldn't mind, maybe you could help clarify? Thanks.

**Comment by matthid** [comment]
yeah, I think the build system is fine but as already mentioned the unit test suite is basically one big integration test interacting with live systems . Therefore it fails from time to time. One can re-try CI with a dummy commit... does this help?

**Comment by matthid** [comment]
looking at the log the reason was that mono crashed on running nuget.exe while downloading nunit therefore it couldnt find nunit later on.... I restarted the build for you, so jo dummy commit required

**Comment by alexreg** [comment]
Yes, the integration testing is not robust for sure. Ideally it would bundle a simple IRC server and test locally, but that’s a lot of effort to set up.

**Comment by paralin** [comment]
This needs a rebase on the new develop branch.

**Comment by paralin** [comment]
The build system has been refactored to DNX which should make sense to you now. It runs under Visual Studio perfectly. Please let me know if you have any questions around this.

In the meantime closing this until you've remade the PR

**Pull request closed without merging**
