### PR TITLE
[Experimental] [Do Not Merge] DNX Project Structure

### PR DESCRIPTION
**Pull request by paralin**
I've implemented a DNX project structure to examine the feasibility, practicality, and pros + cons of restructuring IrcDotNet towards the open-source cross-platform DNX layout, as opposed to FAKE.

Current pros:
 - Can target many different platforms effortlessly (just add to project.json a framework)
 - NuGet and Linux based (builds on default produce NuGet packages)
 - Logical project layout, better structure for samples and tests.
 - Arguably simpler to setup than FAKE.

Current cons:
 - Need to figure out how to target Silverlight with this setup.
 - Docs build system needs to be replaced with something simpler
 - It might be a bit of a jump in the deep end to immediately do a restructure

Example of produced NuGet package:
[IrcDotNet.0.5.0.nuget.zip](https://github.com/IrcDotNet/IrcDotNet/files/129576/IrcDotNet.0.5.0.nuget.zip)

This PR is for notes and discussion around this.

### CODE REVIEW

**Comment by paralin** [comment]
Okay, all tests pass in AppVeyor and Travis. Everything .net 4.0 and up is supported, especially under Mono (the Travis build tests in Mono, AppVeyor under Visual Studio and CoreClr).

Explicitly targeted versions: 
- net40
- net45
- net451
- dnx451

Still todo is to re-implement the documentation generation.

Thoughts @alexreg ?

**Comment by matthid** [comment]
Just my thoughts:

- I think we can/should drop silverlight instead of making that a blocker for this
- Documentation generation:

   The current situation is not optimal, on the other hand we already have a `FSharp.Formatting.CommandLine` package with a standalone runner. Therefore we might be able to setup a runner compatible with coreclr. There probably will be support, but ideally we'd like to wait how FAKE and Paket plan to support it (but we probably can accelerate the FSF support).
- > Arguably simpler to setup than FAKE.

   :(

/cc @tpetricek @forki

**Comment by forki** [comment]
What problems do you have with FAKE?

**Comment by alexreg** [comment]
I have nothing against FAKE, though I know almost nothing about DNX. @matthid was the one who initially put in the FAKE system, so I'll leave you two to debate it for a while. Incidentally, DNX seems to be superseded by https://github.com/dotnet/cli.

**Comment by alexreg** [comment]
Incidentally, why are the 4 checks for the CI?

**Comment by forki** [comment]
FYI there is https://github.com/djanosik/FAKEX

At the moment DNX / dotnetcli are changing on daily basis.

**Comment by alexreg** [comment]
That’s an interesting solution (and compromise).

**Comment by matthid** [comment]
@alexreg because 2 checks (travis+appveyor) are for the branch (https://github.com/IrcDotNet/IrcDotNet/branches) and 2 are for this pr (even though both actually have the same commit hash)

By leaving FAKE in place and using FAKEX we probably can leave the documentation generation in place (there will be problems because of coreclr but I could help out @paralin to make it work if needed)

**Comment by alexreg** [comment]
Okay. I don’t know why it’s building the branches for a PR though… odd.

And yes, I think that solution is best probably. Would be great if you could provide assistance to @paralin.

**Comment by paralin** [comment]
My only thought is - I don't see why FAKE is really needed here. If you look at the Travis script you will see that building the library is really one command now. Do you really need an entire build system just to call one command?

**Comment by forki** [comment]
I'm really just a chicken here, but if I read correctly it's not doing docs anymore. That can probably be solved easily by calling FSharp.Formatting as exe. 

FAKE is used to orchestrate different tools and to make the whole dev / deployment process into one command. There is no big difference in that regard to what DNX wants to do - just differently.

I did over 1000 releases with fake alone in the last year with a lot of completely different deployment processes. You can always script your way out. But if this is the way that you want to go here is the real question.

**Comment by matthid** [comment]
FAKE is not only about building and creating the nuget package:
- Documentation generation
- Creating a release and automate everything
   - Creating a git tag
   - Version bump commit
   - Upload the new nuget package
   - Push the new version of the documentation
   - Managing release notes
   
I think bringing all that those automations to coreClr is way harder because there are no such scripting capabilities that I'm aware of (could be wrong though).

**Comment by forki** [comment]
That's what I meant. Creating nuget packages is only a small part of doing
proper releases. Important, but small and easily scriptable.

**Comment by alexreg** [comment]
@forki, What's this, are you actually recommending against using your own software?! :)

I'm mainly for FAKE, since it is extensible and open to any future expansions of the build process... as long as @paralin doesn't mind using FAKEX, I say let's stay with it, and just modify the Fake script.

**Comment by forki** [comment]
No I'm not against fake. But dnx and coreclr are new situation. We don't
know how things will look like in a couple of weeks. All I know is:
creating nuget packages is only a small part of the story ;-)

**Comment by paralin** [comment]
"FAKE is not only about building and creating the nuget package:"

This is a good point, but this project has had exactly 2 releases, both of which were done manually. I could see having a setup like this for something like [Kuberntes](http://github.com/kubernetes/kubernetes) where there are hundreds of commits a day and many micro CI releases a day, but even there they make their major releases by hand. 

So in reality all that's done here is:
 - Make NuGet Package
 - Upload it to Nuget.org
 - Make git tag
 - Write release notes
 - Compile documentation

Everything but compiling documentation and making the nuget package is done manually anyway, at least right now. And that's totally fine for the speed of releases here.

So having an entire F# language scripting system and 40+ files in the repo - just to automate making documentation and a NuGet package - is this really worth it? I know all of the random build scripts are confusing to newer users who just want to understand the library. And I'm happy to do the work of tagging a git commit to release manually. It's not the most demanding task.

**Comment by paralin** [comment]
@alexreg I would prefer to stay with DNX for now as DNX is quite established (in use in a lot of projects). The dotnet cli is very new and doesn't seem to have the tight integration into Visual Studio that DNX has. 

@forki They're changing in their development branches on a daily basis but in terms of API and the release versions I'm using here they have not changed in the year that I've been using DNX.

**Comment by alexreg** [comment]
Okay. I don’t necessarily like the tight integration with VS though. I mean, it’s fine, but only as long as it’s also fine to build from the command line (at least via MSBuild) and on Mono. If so, then go for it. You may need to add scripts to auto-build the documentation though.

**Comment by matthid** [comment]
> This is a good point, but this project has had exactly 2 releases, both of which were done manually. 

That's exactly the reason why I added FAKE in the first place. A fast release cycle is a good thing. Not doing a release because a small change is not worth the manual release steps is worse than having some infrastructure scripts in the repository. 

Just my two cents. I can totally see your argument though. I'm glad this project gets new life with a new maintainer so you totally should do it in a way that works best for you. :)

**Comment by paralin** [comment]
@alexreg It's tightly integrated in that Visual Studio automatically calls the commands "dnu restore" and "dnu build" and "dnx run". So you don't have to worry about restoring packages when you change the project.json. Other than that it behaves exactly the same on Linux as Windows which I like.

**Comment by paralin** [comment]
@matthid I think the reason why the release cycle is slow here is not due to the publish process being laborious but because there's been very little development on this project in a long time.

What you're talking about is Continuous Integration which is good practice but I think in the case of a library it's not too necessary. If you were publishing to, say, a docker image, the latest version of your server that you would then promote to prod later, it would make more sense. In the scope of a library though, publishing whenever tests pass is, IMO, not the best choice. 

I publish a lot of releases on another library here: https://github.com/paralin/Dota2/releases and don't use any kind of automatic publishing system. It could be useful to auto-publish when a release tag is made. But I think every single build is a bit excessive.

**Comment by alexreg** [comment]
Yep. A 0.6.0 release is probably due almost immediately, and then a 1.0.0 shortly thereafter!

**Comment by paralin** [comment]
Documentation now builds properly, and is updated on the GitHub pages. Merging as I'm pushing for a 0.6.0 release tonight.

Make issues for any new problems, please.

**Comment by forki** [comment]
> an entire F# language scripting system and 40+ files in the repo

I'm curious. Where did all the files come from? Fake is usually one build.fsx file + one nuget package. 

>I would prefer to stay with DNX for now as DNX is quite established 

;-)

**Comment by paralin** [comment]
@forki buildConfig, build, buildDocumentation, AssemblyShared.cs, build.sh, build.cmd, numerous random test files and windows specific code, ....

**Comment by matthid** [comment]
@forki I'm to blame here because I like to have documentation generation at the root level, because I think it belongs to the build infrastructure. And I like to factor out a shared "buildConfig.fsx" `#load`ed by `build.fsx` and `buildDocumentation.fsx` such that I don't have to define some common variables at multiple places.... But it seems to confuse people :(

@paralin
> What you're talking about is Continuous Integration which is good practice but I think in the case of a library it's not too necessary.

No I wasn't talking about CI builds doing releases on every builds, I still was talking about manual releases. IMHO they should be as simple as `./build.sh Release`, just because it makes you release more often automatically. I think this is reason enough (not even considering forgetting things in the manual process like creating the git tag, pushing the tag, updating the docs, pushing the docs branch or whatever).

**Pull request merged**
