### PR TITLE
send an irc raw message event args instance when using the public raw…

### PR DESCRIPTION
**Pull request by ransagy**
… message sending method, Otherwise `StandardIRCClient`'s `OnSendCompleted` with throw an exception later on.

### CODE REVIEW

**Comment by ransagy** [comment]
I'm not sure how maintained this is, but i figured it was worth the try. @paralin as the last accepted PR author, who do we talk to about these?

**Comment by paralin** [comment]
https://github.com/IrcDotNet/IrcDotNet/issues/56

**Comment by ransagy** [comment]
@paralin removed the unintended spacing changes; Now i know how git patch works :)

**Comment by paralin** [comment]
@ransagy Please do something like:

```
git fetch origin
git rebase -i origin/master
```
Rebase your commits down, here is a good reference: https://medium.com/inloopx/rebase-your-branches-like-you-brush-your-teeth-69765009c320

**Comment by ransagy** [comment]
OK, Should be squashed to just a single commit now, It's certainly an atomic enough of a change.

**Comment by paralin** [comment]
@ransagy Or you can do in your /etc/profile.d or whatever:

export VISUAL=nano
export EDITOR=nano

Or whatever. I use emacs/spacemacs/vim so I would recommend leaving it on Vim but that's just me :D

**Comment by paralin** [comment]
I'd recommend reading this: https://medium.com/@preslavrachev/what-s-with-the-50-72-rule-8a906f61f09c

Commit approved, will merge once we fix the tests

**Pull request merged**
