### PR TITLE
Added netcoreapp1.0 to project.json and fixed the code

### PR DESCRIPTION
**Pull request by falcon0**
By default all ASP.NET Core projects seem to use netcoreapp1.0 standard, both when generated using visual studio and yeoman. I've added this to project.json for compatibility sake

### CODE REVIEW

**Comment by paralin** [comment]
cc @DarkKilauea can you test?

**Comment by DarkKilauea** [comment]
`netcoreapp` is intended to be used only for executables or libraries that target only .NET Core, which is why I excluded it from the main project.  You really shouldn't have to make this change in order to use it and it makes using this library in the .NET Framework and Xamarin (when they eventually support `netstandard`) more difficult.

Keep in mind that yeoman templates are usually targeted towards making executables, which is why `netcoreapp` makes sense there.  It's possible the "Class Library" template is different (it really should be or that is a mistake on someone's part).

Source: https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-core-applications.md

> Q: Why is there only one version of .NETCoreApp (1.0), but there are many of .NETStandard?
A: .NETStandard is an abstract representation of API that covers all historical platforms that have ever supported that API. .NETCoreApp represents a concrete application type with a runnable implementation. We are shipping one version of this implementation at this point and it supports netstandard1.6. As we version .NETStandard in the future we will update the implementation of .NETCoreApp to support the new API and ship a new version of .NETCoreApp.

> Q: How is this different than .NETStandard?
A: The NETStandard target framework is an abstract target framework that represents API surface of many frameworks and platforms. As such NETStandard assemblies can run on any platform that supports the NETStandard targeted by that assembly, for example: .NET Desktop, Windows Phone, Universal Windows Platform applications, .NET Core applications, etc. NETCoreApplication is a concrete target framework that represents a single platform with both API surface and implementation. .NET Core applications are runnable on their own. .NETStandard libraries must be published-for or consumed-by a specific concrete target framework to be used in that type of application.

**Comment by falcon0** [comment]
As far as I understood your comment, IrcDotNet should basically work with programs compiled against netcoreapp out of the box, as it should "implement" netstandard1.6 which is a superset of netstandard1.5 which is supported by IrcDotNet. I don't know why, but this is not the case, netcoreapp is not recognized as netstandard1.6 or 1.5, otherwise I wouldn't make this pull request, would I?
I also disagree with your statement it'll make using this library more difficult for 3rd parties. I didn't change other framework targets, I just added another one, hence as far as I understand it it shouldn't affect anybody depending on other targets.
If you can tell me how to integrate this lib into freshly generated asp.net core mvc 6 project then yes, this pull request makes no sense.

I did test it, I was able to connect to quakenet server, join channel and intercept and send messages.

**Comment by DarkKilauea** [comment]
When I get home I will attempt to get this working for MVC core.  For my own project, I had to build the NuGet packages manually, then import them into my project due to a bug in how dotnet build discovers dependencies that are nested too far directory wise (in that case I'm was using a git submodule).

I will try out your patch in my situation as well to see if that fixes it, but according to the published docs, netstandard really should be all that is required.  There are also several popular packages available on NuGet which are shipping .netstandard as their only framework for .net core support.

**Comment by paralin** [comment]
Thank you for your PR. See #35. 

Superceded

**Pull request closed without merging**
